### ISSUE TITLE
`Proof::from_slice` is not working in `release-0.6`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/plonk#447]
It seems `Proof` returns Plonk's Error that does not implement the required trait for `from_slice`:

```
 let proof = Proof::from_slice(&proof[..]).expect("a Proof");

> the trait `dusk_bytes::BadLength` is not implemented 
> for `dusk_plonk::prelude::Error`
```
